### PR TITLE
Refactored some simple stuff

### PR DESCRIPTION
**Pull request by ghost**
Just some simple refactoring. Haven't changed the flow of things (only one new method: `moveMootools()`).

You will probably need to test this a bit :)

### CODE REVIEW

**Comment by jissereitsma** [comment]
I'm actually busy myself now with refactoring the same file. So your source is no longer up to date :(

**Comment by ghost** [comment]
Ok, dump it :)

**Comment by jissereitsma** [comment]
Damn it. Thanks anyway. I have a lot of refactoring to do these days, so really appreciate the work you've done. Let me get you a cup of coffee at #jd16nl

**Comment by ghost** [comment]
Don't drink coffee, I'll take a tea ;)

PS: The reason I came across the v=1.2.3 issue, was because my extensions now add the version number by default to their css/js files.
This to prevent stuff breaking when html output changes and css/js files still get served from cache (without the new changes).

**Pull request closed without merging**
